// GENERATED by store/legal/build.py from store/legal/content.py - do not edit.
// ignore_for_file: prefer_single_quotes

import 'legal_model.dart';

const legalEmail = 'info@gezip.app';

const privacyPolicy = LegalDoc(
  title: 'Gizlilik Politikası',
  updated: '19 Eylül 2026',
  lead: '**Girdiğin kartlar ve kayıtlar hiçbir zaman toplanmaz, bir sunucuya gönderilmez ve kimseyle paylaşılmaz.** Yalnızca kendi cihazında kalır. Uygulamada hesap, reklam, analiz aracı ya da takip yoktur.',
  sections: [
    LegalSection('Genel Bakış', [
      LegalBlock.p('Bu gizlilik politikası, **Kaç Gün Oldu?** uygulamasının (“Uygulama”) bilgilerini nasıl ele aldığını açıklar. Uygulama, bir şeyi en son ne zaman yaptığını takip etmen için tasarlanmış, tamamen çevrimdışı çalışan bir araçtır.'),
      LegalBlock.p('Uygulamayı kullanmak için hesap oluşturman, giriş yapman ya da herhangi bir kişisel bilgi vermen gerekmez. Uygulama hiçbir ağ bağlantısı kurmaz.'),
    ]),
    LegalSection('Toplanan Veriler', [
      LegalBlock.p('**Hiçbir kişisel veri toplanmaz.** Özellikle:'),
      LegalBlock.list([
        'Ad, e-posta adresi, telefon numarası gibi kimlik bilgileri toplanmaz',
        'Konum, kişiler, fotoğraflar, takvim, mikrofon ya da kamera bilgisi toplanmaz',
        'Kartların ve kayıt tarihlerin geliştiriciye ya da başka bir tarafa gönderilmez',
        'Reklam kimliği, analiz ya da çökme raporu gibi hiçbir izleme verisi toplanmaz',
      ]),
    ]),
    LegalSection('Cihazında Saklanan Bilgiler', [
      LegalBlock.p('Uygulamayı kullanırken girdiğin bilgiler yalnızca **kendi cihazında**, işletim sisteminin uygulamalara ayırdığı korumalı depolama alanında saklanır. Cihazındaki başka uygulamalar bu alana erişemez:'),
      LegalBlock.list([
        'Oluşturduğun kartlar: ad, simge, seçtiğin sıklık ve hatırlatma tercihi',
        'Her karta işaretlediğin tarihler',
        'İsteğe bağlı olarak girdiğin ad ve kullanıcı adı (yalnızca profil ekranında görünür)',
        'Uygulama tercihlerin: renk teması, kart düzeni (ızgara ya da liste), hatırlatma saati',
      ]),
      LegalBlock.p('Bu bilgilere geliştirici dahil hiç kimse erişemez.'),
    ]),
    LegalSection('Yedekleme', [
      LegalBlock.p('Uygulama kendi başına hiçbir buluta yedekleme yapmaz. Ancak işletim sistemlerinin kendi yedekleme özellikleri (Android\'de Google hesabına yedekleme, iOS\'ta iCloud ve bilgisayar yedekleri) açıksa, uygulama verilerin bu yedeğe dahil edilebilir. Bu yedek senin Google ya da Apple hesabın altında ilgili şirket tarafından yönetilir ve geliştiricinin erişimine açık değildir.'),
      LegalBlock.p('Ayrıca dilersen **Ayarlar → Yedeği panoya kopyala** ile verilerini metin olarak kopyalayabilir, başka bir cihazda **Panodaki yedeği geri yükle** ile içeri alabilirsin. Bu yedek şifrelenmemiş düz metindir; nereye yapıştıracağın sana bağlıdır.'),
    ]),
    LegalSection('Pano Kullanımı', [
      LegalBlock.p('Uygulama panoya yalnızca sen “Yedeği panoya kopyala”ya ya da “Panodaki yedeği geri yükle”ye dokunduğunda erişir. Başka hiçbir zaman panonu okumaz. Bazı Android ve iOS sürümleri, bir uygulama panoya eriştiğinde seni bilgilendirir; bu beklenen bir davranıştır.'),
    ]),
    LegalSection('Hatırlatmalar', [
      LegalBlock.p('Bir karta “Bana hatırlat” dediğinde, kartın sırası geldiğinde seçtiğin saatte bir bildirim gösterilir. Bildirimler tamamen **cihazında** planlanır: zaman ve gösterilecek metin işletim sisteminin kendi bildirim sistemine verilir, hiçbir sunucuya gönderilmez. Uygulama anlık bildirim (push) altyapısı kullanmaz ve bildirim jetonu üretmez.'),
      LegalBlock.p('Bildirimde kartının adı görünür; yani kilit ekranında okunabilir hâle gelebilir. Hassas bir kart adı için hatırlatmayı kapalı tutmayı tercih edebilirsin.'),
      LegalBlock.p('Bildirimler için işletim sistemi izni gerekir. Bu izin, ilk hatırlatmayı açtığında istenir; uygulamayı ilk açtığında istenmez. İznin dilediğin zaman telefon ayarlarından geri alınabilir; vermezsen uygulamanın geri kalanı olduğu gibi çalışır. Android\'de hatırlatmalar tam zamanlı alarm izni gerektirmeyecek şekilde planlanır, bu yüzden bildirim hedeflenen saatten birkaç dakika sonra gelebilir.'),
    ]),
    LegalSection('Üçüncü Taraf Hizmetler', [
      LegalBlock.p('Uygulama; reklam ağı, analiz aracı, çökme raporlama aracı, sosyal medya bileşeni ya da kullanıcı verisi toplayan herhangi bir üçüncü taraf yazılım geliştirme kiti (SDK) içermez. Uygulamada kullanılan yazı tipleri uygulamanın içinde paketlidir; internetten indirilmez.'),
      LegalBlock.p('Uygulamayı indirdiğin mağaza (Google Play ya da Apple App Store) indirme işlemine ilişkin kendi gizlilik politikası kapsamında bilgi işleyebilir; bu, Uygulama\'nın dışındadır.'),
    ]),
    LegalSection('İzinler', [
      LegalBlock.p('Uygulama; kamera, mikrofon, konum, kişiler, takvim ya da fotoğraf izni istemez ve internet izni kullanmaz.'),
      LegalBlock.list([
        '**Bildirim izni:** yalnızca hatırlatma kurduğunda istenir',
        '**Açılışta çalışma (Android):** telefon yeniden başladığında planlanmış hatırlatmaların yeniden kurulabilmesi için',
        '**Titreşim (Android):** bildirim geldiğinde',
      ]),
    ]),
    LegalSection('Verilerinin Silinmesi', [
      LegalBlock.p('Verilerin tamamı senin denetimindedir. Tek tek kartları ve kayıtları uygulama içinden silebilir, **Ayarlar → Bütün kartları sil** ile hepsini tek seferde kaldırabilirsin. Uygulamayı cihazından kaldırdığında uygulamaya ait tüm yerel veriler de silinir.'),
      LegalBlock.p('Geliştiricide saklanan hiçbir verin olmadığı için ayrıca bir silme talebi göndermene gerek yoktur. İşletim sisteminin bulut yedeği açıksa, o yedekteki kopya ilgili Google ya da Apple hesabından ayrıca silinebilir.'),
    ]),
    LegalSection('Güvenlik', [
      LegalBlock.p('Verilerin işletim sisteminin uygulama sanal alanı (sandbox) ile korunur. Uygulama verileri ayrıca kendi başına şifrelemez; güvenlik cihazının ekran kilidi ve cihaz şifrelemesi ayarlarına bağlıdır. Cihazında ekran kilidi kullanmanı öneririz.'),
    ]),
    LegalSection('Çocukların Gizliliği', [
      LegalBlock.p('Uygulama çocuklara yönelik olarak pazarlanmaz. Uygulama hiç kimseden, çocuklar dahil, kişisel veri toplamaz.'),
    ]),
    LegalSection('Yasal Haklarım', [
      LegalBlock.p('6698 sayılı KVKK, GDPR ve benzeri veri koruma mevzuatı kapsamında erişim, düzeltme, silme ve itiraz haklarına sahipsin. Geliştirici kişisel verini işlemediği için bu haklar bakımından karşılanacak bir veri yoktur; bütün bilgilerin cihazındadır ve tümüyle senin denetimindedir.'),
      LegalBlock.callout('Soru ya da talebin olursa info@gezip.app adresine yazabilirsin.'),
    ]),
    LegalSection('Politikadaki Değişiklikler', [
      LegalBlock.p('Bu politika güncellenirse güncel metin uygulamanın yeni sürümüyle ve bu sayfada yayımlanır, yukarıdaki güncelleme tarihi değiştirilir. Veri işleme uygulamalarımızda esaslı bir değişiklik olursa bu, sürüm notlarında belirtilir.'),
    ]),
    LegalSection('İletişim', [
      LegalBlock.p('Bu politika ya da uygulamanın gizlilik uygulamaları hakkındaki soru ve talepler için:'),
      LegalBlock.contact(),
    ]),
  ],
);

const termsOfUse = LegalDoc(
  title: 'Kullanım Koşulları',
  updated: '19 Eylül 2026',
  lead: '**Kaç Gün Oldu?** ücretsiz, çevrimdışı ve kişisel kullanım içindir. Verilerin yalnızca senin cihazında durur; bu yüzden **yedeklemek senin sorumluluğundadır** ve hatırlatmalar **kritik işler için tek başına güvenilecek bir araç değildir.** Aşağıda bunlar ve diğer koşullar var.',
  sections: [
    LegalSection('Kabul', [
      LegalBlock.p('Uygulamayı indirerek, kurarak ya da kullanarak bu Kullanım Koşulları\'nı kabul etmiş olursun. Kabul etmiyorsan uygulamayı kullanma ve cihazından kaldır.'),
    ]),
    LegalSection('Hizmetin Tanımı', [
      LegalBlock.p('**Kaç Gün Oldu?**, EMA Labs tarafından geliştirilen; bir şeyi en son ne zaman yaptığını kaydetmene, üzerinden kaç gün geçtiğini görmene ve isteğe bağlı hatırlatma almana yarayan bir mobil uygulamadır. Uygulama ücretsizdir, hesap gerektirmez ve internet bağlantısı olmadan çalışır.'),
    ]),
    LegalSection('Lisans', [
      LegalBlock.p('EMA Labs sana, Uygulama\'yı kendi cihazlarında kişisel amaçla kullanman için kişisel, devredilemez, münhasır olmayan ve geri alınabilir bir lisans verir. Uygulama sana satılmaz, yalnızca kullanım hakkı lisanslanır.'),
    ]),
    LegalSection('Senin Verilerin', [
      LegalBlock.p('Girdiğin kartlar, kayıtlar ve diğer bilgiler sana aittir. Bunlar yalnızca cihazında saklanır; EMA Labs bunlara erişemez, bunları göremez ve geri getiremez. Girdiğin bilgilerden ve bunları nasıl kullandığından sen sorumlusun. Ayrıntılar için Gizlilik Politikası\'na bak.'),
    ]),
    LegalSection('Yedekleme ve Veri Kaybı', [
      LegalBlock.p('Verilerin bir sunucuda tutulmadığı için, **uygulamayı silmen, telefonunu değiştirmen, cihazı sıfırlaman ya da cihazın bozulması hâlinde verilerin geri gelmez** (işletim sisteminin bulut yedeği açıksa ve o yedekten geri yüklersen hariç).'),
      LegalBlock.p('Bu yüzden önemli verilerini korumak için **Ayarlar → Yedeği panoya kopyala** özelliğini kullanıp yedeği güvenli bir yere (ör. notlar uygulaman ya da e-posta) kaydetmeni öneririz. EMA Labs, veri kaybından doğan zararlardan, kanunen sınırlanamayan haller dışında sorumlu tutulamaz.'),
    ]),
    LegalSection('Hatırlatmalar ve Hesaplamalar', [
      LegalBlock.p('Hatırlatmalar **elinden geldiğince** (best-effort) gösterilir. Telefonun pil tasarrufu, “rahatsız etme” modu, uygulama kısıtlamaları, kapatılmış bildirim izni ya da işletim sisteminin zamanlama sınırları nedeniyle bildirim gecikebilir ya da hiç gelmeyebilir.'),
      LegalBlock.p('Uygulamanın gösterdiği süreler, ritim ve “gecikti” gibi durumlar, senin girdiğin tarihlerden yapılan **basit tahminlerdir**; kişisel kolaylık içindir. Uygulamayı **ilaç kullanımı, sağlık kontrolü, güvenlik, hukuki süre, ödeme ya da benzeri kritik yükümlülükler için tek başına kullanma**; bunlar için ayrıca alarm, takvim ya da ilgili kurumun hatırlatmalarını kullan.'),
    ]),
    LegalSection('Kabul Edilebilir Kullanım', [
      LegalBlock.p('Uygulamayı yalnızca hukuka uygun biçimde ve bu koşullara göre kullanabilirsin. Şunları yapamazsın:'),
      LegalBlock.list([
        'Uygulamayı kopyalamak, satmak, kiralamak ya da başkalarına dağıtmak',
        'Yasaların açıkça izin verdiği ölçü dışında, uygulamanın kaynak kodunu çıkarmaya, tersine mühendislik yapmaya ya da değiştirmeye çalışmak',
        'Uygulamadaki telif ya da marka bildirimlerini kaldırmak',
        'Uygulamayı yasa dışı bir amaçla kullanmak',
      ]),
    ]),
    LegalSection('Fikri Mülkiyet ve Açık Kaynak', [
      LegalBlock.p('Uygulamanın tasarımı, kodu, simgesi ve adı EMA Labs\'e aittir. Uygulama; Flutter ve çeşitli açık kaynak paketlerle, ayrıca **Instrument Serif** ve **Archivo** yazı tipleriyle (SIL Açık Yazı Tipi Lisansı 1.1) yapılmıştır. Bu bileşenlerin lisans metinleri uygulamada **Ayarlar → Açık kaynak lisansları** altında görülebilir.'),
    ]),
    LegalSection('Garanti Reddi', [
      LegalBlock.p('Uygulama “olduğu gibi” ve “mevcut haliyle” sunulur. Yasaların izin verdiği en geniş ölçüde EMA Labs, kesintisiz ya da hatasız çalışacağına, hatırlatmaların zamanında geleceğine ya da belirli bir amaca uygun olacağına dair açık ya da örtülü hiçbir garanti vermez.'),
    ]),
    LegalSection('Sorumluluğun Sınırlanması', [
      LegalBlock.p('Yasaların izin verdiği en geniş ölçüde EMA Labs, uygulamanın kullanımından ya da kullanılamamasından doğan dolaylı, arızi ya da sonuç olarak ortaya çıkan zararlardan (veri kaybı, kaçırılan bir hatırlatma dahil) sorumlu değildir. **Kasıt ve ağır kusur hâlleri ile, 6502 sayılı Tüketicinin Korunması Hakkında Kanun dahil, kanunen sınırlanamayan sorumluluk ve haklar bu maddeden etkilenmez.**'),
    ]),
    LegalSection('Değişiklikler ve Sonlandırma', [
      LegalBlock.p('Uygulamayı ve bu koşulları zaman zaman güncelleyebiliriz. Güncel koşullar uygulamada ve bu sayfada yayımlanır; esaslı değişiklikten sonra uygulamayı kullanmaya devam etmen, güncel koşulları kabul ettiğin anlamına gelir. Uygulamayı dilediğin zaman kaldırarak kullanımı sonlandırabilirsin.'),
    ]),
    LegalSection('Google Play ve Apple App Store', [
      LegalBlock.p('Bu koşullar yalnızca senin ve EMA Labs arasındadır; Google ya da Apple bu koşulların tarafı değildir ve uygulamanın bakımı, desteği ya da garantisinden sorumlu değildir. **iOS\'ta** Apple\'ın standart Lisanslı Uygulama Sonlandırma Sözleşmesi (Apple standart EULA) bu koşullara ek olarak geçerlidir; bu koşullar onun yerine geçmez. Apple ve yan kuruluşları, bu koşulların senin lehine üçüncü taraf yararlanıcılarıdır.'),
    ]),
    LegalSection('Uygulanacak Hukuk', [
      LegalBlock.p('Bu koşullara Türkiye Cumhuriyeti hukuku uygulanır. Tüketici işlemlerinde, kanunla belirlenen tüketici hakem heyetleri ve tüketici mahkemeleri yetkilidir; yaşadığın ülkedeki zorunlu tüketici koruma hükümleri saklıdır.'),
    ]),
    LegalSection('İletişim', [
      LegalBlock.p('Bu koşullar hakkındaki soruların için:'),
      LegalBlock.contact(),
    ]),
  ],
);

