import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kac_gun_oldu/domain/card.dart';
import 'package:kac_gun_oldu/domain/date.dart';
import 'package:kac_gun_oldu/services/home_widgets.dart';
import 'package:kac_gun_oldu/state/card_store.dart';
import 'package:kac_gun_oldu/theme/tokens.dart';
import 'package:kac_gun_oldu/widgets/card_glyph.dart';
import 'package:shared_preferences/shared_preferences.dart';

class FakeHomeWidgets implements HomeWidgets {
  final published = <Map<String, Object?>>[];

  /// Handed over (once) by the next [takeMarks].
  List<WidgetMark> marks = [];
  final pins = <({String? cardId, bool list})>[];

  @override
  Future<void> publish(String snapshot) async {
    published.add(jsonDecode(snapshot) as Map<String, Object?>);
  }

  @override
  Future<List<WidgetMark>> takeMarks() async {
    final taken = marks;
    marks = [];
    return taken;
  }

  @override
  Future<bool> canPin() async => true;

  @override
  Future<PinResult> pin({String? cardId, bool list = false}) async {
    pins.add((cardId: cardId, list: list));
    return PinResult.requested;
  }

  @override
  Future<void> openPinPermission() async {}

  final pinnedEvents = StreamController<void>.broadcast();

  @override
  Stream<void> get pinned => pinnedEvents.stream;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final t = todayKey();
  List<Map<String, Object?>> cardsOf(Map<String, Object?> snapshot) =>
      (snapshot['cards'] as List).cast<Map<String, Object?>>();

  group('widgetSnapshot', () {
    test('holds each card\'s last record and interval, not day counts', () {
      final snapshot = jsonDecode(widgetSnapshot([
        Card(
          id: 'p',
          name: 'Bitkileri suladım',
          recs: [shiftDays(t, -2), shiftDays(t, -6), shiftDays(t, -9)],
        ),
        Card(id: 'b', name: 'Berber', recs: [shiftDays(t, -20)], every: 30, icon: 'scissors'),
        const Card(id: 'n', name: 'Yeni', recs: []),
      ], t)) as Map<String, Object?>;

      expect(snapshot['v'], widgetSnapshotVersion);
      final cards = cardsOf(snapshot);
      // Median of the gaps 4 and 3, learned from the records.
      expect(cards[0], {
        'id': 'p',
        'name': 'Bitkileri suladım',
        'icon': 'plant',
        'last': shiftDays(t, -2),
        'typical': 4,
      });
      // A declared rhythm wins; one record is enough then.
      expect(cards[1]['typical'], 30);
      expect(cards[1]['icon'], 'scissors');
      expect(cards[2]['last'], isNull);
      expect(cards[2]['typical'], isNull);
    });

    test('carries the current theme\'s colours for every tier', () {
      final snapshot = jsonDecode(widgetSnapshot(const [], t)) as Map<String, Object?>;
      final tiers = snapshot['tiers'] as Map<String, Object?>;
      expect(tiers.keys, containsAll(['fresh', 'calm', 'soon', 'late']));
      final late = tiers['late'] as Map<String, Object?>;
      expect(late['bg'], AppColor.primary.toARGB32());
      expect((snapshot['theme'] as Map)['surface'], AppColor.surface.toARGB32());
    });
  });

  test('every card glyph has its native widget copy', () {
    // Generated by tool/gen_widget_glyphs.py; re-run it after changing the
    // catalog, or widgets fall back to the spark glyph.
    for (final key in cardGlyphs.keys) {
      expect(File('android/app/src/main/res/drawable/wg_$key.xml').existsSync(), isTrue, reason: key);
      expect(
        File('ios/KacGunOlduWidget/Assets.xcassets/glyph_$key.imageset/glyph_$key.svg').existsSync(),
        isTrue,
        reason: key,
      );
    }
  });

  test('parseWidgetMarks keeps the well-formed marks only', () {
    expect(
      parseWidgetMarks('[{"id":"p","day":"2026-09-18"},{"id":"x"},{"id":"q","day":"dün"},5]'),
      [(id: 'p', day: '2026-09-18')],
    );
    expect(parseWidgetMarks(null), isEmpty);
    expect(parseWidgetMarks('bozuk'), isEmpty);
  });

  test('cardIdFromLink reads the full URL and the bare path alike', () {
    expect(cardIdFromLink(Uri.parse('kacgunoldu://app/card/abc')), 'abc');
    expect(cardIdFromLink(Uri.parse('/card/abc')), 'abc');
    expect(cardIdFromLink(Uri.parse('/')), isNull);
    expect(cardIdFromLink(Uri.parse('kacgunoldu://app/other/abc')), isNull);
  });

  group('CardStore', () {
    Future<void> withStore(
      FakeHomeWidgets fake,
      Future<void> Function(CardStore store) body, {
      Map<String, Object> prefs = const {},
    }) async {
      SharedPreferences.setMockInitialValues({
        ...prefs,
        'nezaman.cards.v1': jsonEncode([
          {'id': 'p', 'name': 'Bitkileri suladım', 'recs': [shiftDays(t, -2)]},
        ]),
      });
      final store = CardStore(homeWidgets: fake);
      await store.init();
      try {
        await body(store);
      } finally {
        store.dispose();
      }
    }

    test('publishes at start, on every change and on a theme switch', () async {
      final fake = FakeHomeWidgets();
      await withStore(fake, (store) async {
        expect(fake.published, hasLength(1));
        expect(cardsOf(fake.published.last).single['last'], shiftDays(t, -2));

        store.record('p', 0);
        expect(fake.published, hasLength(2));
        expect(cardsOf(fake.published.last).single['last'], t);

        final other = palettes.firstWhere((p) => p.id != store.themeId);
        store.setTheme(other.id);
        expect(fake.published, hasLength(3));
        expect(
          (fake.published.last['theme'] as Map)['primary'],
          other.primary.toARGB32(),
        );
        store.setTheme(kiremit.id);
      });
    });

    test('days marked on a widget become records before the first publish', () async {
      final fake = FakeHomeWidgets()
        ..marks = [
          (id: 'p', day: t),
          (id: 'p', day: t), // tapped twice: one record
          (id: 'gone', day: t), // deleted since
        ];
      await withStore(fake, (store) async {
        expect(store.byId('p')!.recs, [t, shiftDays(t, -2)]);
        // The widgets were never handed the stale snapshot.
        expect(fake.published, hasLength(1));
        expect(cardsOf(fake.published.single).single['last'], t);
        expect(store.snack!.message, "Bitkileri suladım · widget'tan kaydedildi");
      });
    });

    test('marks made while the app was in the background land on resume', () async {
      final fake = FakeHomeWidgets();
      await withStore(fake, (store) async {
        fake.marks = [(id: 'p', day: t)];
        store.didChangeAppLifecycleState(AppLifecycleState.resumed);
        await Future<void>.delayed(Duration.zero);
        expect(store.byId('p')!.recs.first, t);
      });
    });

    test('the "Bugün yaptım" setting reaches the widgets and is remembered', () async {
      final fake = FakeHomeWidgets();
      await withStore(fake, (store) async {
        expect(store.widgetDoneButton, isTrue);
        expect(fake.published.last['doneButton'], isTrue);
        store.setWidgetDoneButton(false);
        expect(fake.published.last['doneButton'], isFalse);
      });
      await withStore(
        FakeHomeWidgets(),
        (store) async => expect(store.widgetDoneButton, isFalse),
        prefs: {'nezaman.widgetdone.v1': false},
      );
    });

    test('a widget can be placed from the app where the launcher allows it', () async {
      final fake = FakeHomeWidgets();
      await withStore(fake, (store) async {
        await Future<void>.delayed(Duration.zero);
        expect(store.canPinWidget, isTrue);
        await store.pinWidget(cardId: 'p');
        await store.pinWidget(list: true);
        expect(fake.pins, [(cardId: 'p', list: false), (cardId: null, list: true)]);

        // Placed (MIUI does it silently): the app says so.
        fake.pinnedEvents.add(null);
        await Future<void>.delayed(Duration.zero);
        expect(store.snack!.message, 'Widget ana ekrana eklendi');
      });
    });

    test('a widget tap opens its card', () async {
      await withStore(FakeHomeWidgets(), (store) async {
        final handled = await store.didPushRouteInformation(
          RouteInformation(uri: Uri.parse('kacgunoldu://app/card/p')),
        );
        expect(handled, isTrue);
        expect(store.openCardRequest.value, 'p');

        final other = await store.didPushRouteInformation(
          RouteInformation(uri: Uri.parse('/somewhere')),
        );
        expect(other, isFalse);

        // A link of ours without a card is still claimed, not routed.
        store.openCardRequest.value = null;
        final bare = await store.didPushRouteInformation(
          RouteInformation(uri: Uri.parse('kacgunoldu://app/')),
        );
        expect(bare, isTrue);
        expect(store.openCardRequest.value, isNull);
      });
    });
  });
}
