"""Home screen widget glyphs, generated from the app's own icons.

The card glyphs in the app are Material icons (lib/widgets/card_glyph.dart)
plus a hand-drawn tooth. Home screen widgets are drawn natively, so they get
vector copies of exactly those shapes:

  android/app/src/main/res/drawable/wg_<key>.xml          (vector drawables)
  ios/KacGunOlduWidget/Assets.xcassets/glyph_<key>.imageset (SVG, template)

Both are white silhouettes; the widgets tint them with the tier's ink.
Run after changing the glyph catalog:

  python tool/gen_widget_glyphs.py

Needs fontTools (pip install fonttools) and the Flutter SDK (for its Material
icon font and icons.dart).
"""

import json
import re
import shutil
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FLUTTER = Path(shutil.which("flutter")).resolve().parent.parent
FONT = FLUTTER / "bin/cache/artifacts/material_fonts/materialicons-regular.otf"
ICONS_DART = FLUTTER / "packages/flutter/lib/src/material/icons.dart"
CATALOG = ROOT / "lib/widgets/card_glyph.dart"
ANDROID = ROOT / "android/app/src/main/res/drawable"
IOS = ROOT / "ios/KacGunOlduWidget/Assets.xcassets"

# _ToothPainter in card_glyph.dart, on its 24-unit grid: a 1.8 stroke.
TOOTH = (
    "M7.2,3.4 C4.4,3.4 3,5.6 3.4,8.6 C3.8,11.4 5.2,12.6 5.8,15.4 "
    "C6.4,18.4 6.8,21 8.4,21 C10.2,21 10.2,15.6 12,15.6 "
    "C13.8,15.6 13.8,21 15.6,21 C17.2,21 17.6,18.4 18.2,15.4 "
    "C18.8,12.6 20.2,11.4 20.6,8.6 C21,5.6 19.6,3.4 16.8,3.4 "
    "C14.8,3.4 13.6,4.6 12,4.6 C10.4,4.6 9.2,3.4 7.2,3.4 Z"
)

# Not card glyphs, but drawn the same way: the widgets' "Bugün yaptım" button.
EXTRA = [("check", "Icons.check_rounded")]

HEADER = "<!-- Generated by tool/gen_widget_glyphs.py - do not edit. -->\n"


def catalog():
    text = CATALOG.read_text(encoding="utf-8")
    block = text[text.index("const cardGlyphs") : text.index("};")]
    return re.findall(r"'(\w+)':\s*(Icons\.\w+|null)", block)


def codepoint(name):
    text = ICONS_DART.read_text(encoding="utf-8")
    m = re.search(rf"static const IconData {name} = IconData\(\s*(0x[0-9a-f]+)", text)
    if not m:
        sys.exit(f"{name} not found in icons.dart")
    return int(m.group(1), 16)


def main():
    font = TTFont(FONT)
    em = font["head"].unitsPerEm
    ascent = font["hhea"].ascent
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()

    for old in ANDROID.glob("wg_*.xml"):
        old.unlink()
    for old in IOS.glob("glyph_*.imageset"):
        shutil.rmtree(old)

    for key, icon in catalog() + EXTRA:
        if icon == "null":
            if key != "tooth":
                sys.exit(f"{key}: no icon and no hand drawing")
            size, fill, stroke = 24, None, TOOTH
        else:
            pen = SVGPathPen(glyphs)
            # Font space is y-up from the baseline; drawables are y-down.
            glyphs[cmap[codepoint(icon[len("Icons."):])]].draw(
                TransformPen(pen, (1, 0, 0, -1, 0, ascent))
            )
            size, fill, stroke = em, pen.getCommands(), None

        path = (
            f'<path android:fillColor="#FFFFFFFF" android:pathData="{fill}"/>'
            if fill
            else '<path android:strokeColor="#FFFFFFFF" android:strokeWidth="1.8" '
            'android:strokeLineCap="round" android:strokeLineJoin="round" '
            f'android:pathData="{stroke}"/>'
        )
        (ANDROID / f"wg_{key}.xml").write_text(
            HEADER
            + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            + '    android:width="24dp" android:height="24dp"\n'
            + f'    android:viewportWidth="{size}" android:viewportHeight="{size}">\n'
            + f"    {path}\n</vector>\n",
            encoding="utf-8",
        )

        svg_path = (
            f'<path fill="#FFFFFF" d="{fill}"/>'
            if fill
            else '<path fill="none" stroke="#FFFFFF" stroke-width="1.8" '
            f'stroke-linecap="round" stroke-linejoin="round" d="{stroke}"/>'
        )
        imageset = IOS / f"glyph_{key}.imageset"
        imageset.mkdir(parents=True)
        (imageset / f"glyph_{key}.svg").write_text(
            f'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" '
            f'viewBox="0 0 {size} {size}">{svg_path}</svg>\n',
            encoding="utf-8",
        )
        (imageset / "Contents.json").write_text(
            json.dumps(
                {
                    "images": [{"filename": f"glyph_{key}.svg", "idiom": "universal"}],
                    "info": {"author": "xcode", "version": 1},
                    "properties": {
                        "preserves-vector-representation": True,
                        "template-rendering-intent": "template",
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        print(key)


if __name__ == "__main__":
    main()
