"""
Launch animation mark for Android, generated from the app icon's geometry.

`gen.py` draws the launcher icon with PIL: a ring (outer radius 310, stroke
140, 54 degree gap centred at 12 o'clock) and a "?" in Instrument Serif at
380px, its dot at `CY - 380 * 0.18` and its ink centred horizontally. This
script takes the "?" outline straight from the font file, laid out exactly
as gen.py lays it out, so the launch animation and the icon can never drift
apart.

Run:  python assets/icon/gen_splash.py   (needs `pip install fonttools`)
Writes android/.../drawable/ic_splash_mark.xml, the vector that
avd_splash_mark.xml animates and MainActivity shows while the app starts.
"""
import math
import os

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
FONT = os.path.join(ROOT, "assets", "fonts", "InstrumentSerif_400Regular.ttf")
OUT_XML = os.path.join(
    ROOT, "android", "app", "src", "main", "res", "drawable", "ic_splash_mark.xml"
)

# --- icon geometry (assets/icon/gen.py, 1024 canvas) -----------------------
CX = CY = 512
RING_OUTER_R = 310
RING_STROKE = 140
GAP_DEG = 54
GLYPH_PX = 380
DOT_ABOVE_CENTRE = (RING_OUTER_R + RING_STROKE / 2) * 0.18   # gen.py: outer_r * 0.18

# --- Android splash icon: 288dp canvas, only the central 192dp circle shows -
CANVAS_DP = 288
RING_DP = 130                                    # ring outer diameter on screen
SCALE = round(RING_DP / (RING_OUTER_R * 2), 5)

def r(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def glyph_path():
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("?")]
    k = GLYPH_PX / font["head"].unitsPerEm

    bp = BoundsPen(glyphs)
    glyphs[name].draw(bp)
    xmin, ymin, xmax, ymax = bp.bounds
    gw, gh = (xmax - xmin) * k, (ymax - ymin) * k

    dot_y = CY - DOT_ABOVE_CENTRE
    left = CX - gw / 2
    top = dot_y - gh

    # font units (y up) -> icon pixels (y down)
    matrix = (k, 0, 0, -k, left - xmin * k, top + ymax * k)
    pen = SVGPathPen(glyphs, ntos=lambda v: r(v))
    glyphs[name].draw(TransformPen(pen, matrix))
    return pen.getCommands(), (left, top, gw, gh)


def ring_path():
    centre_r = RING_OUTER_R - RING_STROKE / 2        # PIL strokes inward
    a0 = math.radians(-90 + GAP_DEG / 2)
    a1 = math.radians(-90 - GAP_DEG / 2)
    x0, y0 = CX + centre_r * math.cos(a0), CY + centre_r * math.sin(a0)
    x1, y1 = CX + centre_r * math.cos(a1), CY + centre_r * math.sin(a1)
    return f"M{r(x0)},{r(y0)} A{r(centre_r)},{r(centre_r)} 0 1,1 {r(x1)},{r(y1)}"


def write_xml(q):
    shift = CANVAS_DP / 2 - CX * SCALE
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- GENERATED by assets/icon/gen_splash.py - edit that, not this file.",
        "     The launcher icon's ring and \"?\", white, for Android's launch screen. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{CANVAS_DP}dp"',
        f'    android:height="{CANVAS_DP}dp"',
        f'    android:viewportWidth="{CANVAS_DP}"',
        f'    android:viewportHeight="{CANVAS_DP}">',
        "    <group",
        f'        android:scaleX="{SCALE}"',
        f'        android:scaleY="{SCALE}"',
        f'        android:translateX="{r(shift)}"',
        f'        android:translateY="{r(shift)}">',
        "        <path",
        '            android:name="ring"',
        f'            android:pathData="{ring_path()}"',
        '            android:strokeColor="#FFFFFF"',
        f'            android:strokeWidth="{RING_STROKE}"',
        '            android:trimPathEnd="1" />',
        '        <group android:name="mark">',
        "            <path",
        '                android:name="q"',
        '                android:fillColor="#FFFFFF"',
        '                android:fillAlpha="1"',
        f'                android:pathData="{q}" />',
        "        </group>",
        "    </group>",
        "</vector>",
        "",
    ]
    with open(OUT_XML, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", OUT_XML)


def main():
    q, (left, top, gw, gh) = glyph_path()
    write_xml(q)
    print(f"glyph ink {gw:.0f}x{gh:.0f}px at ({left:.0f},{top:.0f}); scale {SCALE}")


if __name__ == "__main__":
    main()
